apiVersion: v1
kind: Config

clusters:
  - name: my-kube
    cluster:
      certificate-authority: ca.crrt
      server: https://my-kube:6443

contexts:
  - name: my-kube-admin@my-kube
    context:
      cluster: my-kube
      user: my-kube-admin
  - name: admin@East-Region
  - name: dev@Google-Cloud

users:
  - name: my-kube-admin
    context:
      client-certificate: admin.crt
      client-key: admin.key
  - name: admin
  - name: dev
