apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list","create","update","delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]

---
# Depends on namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-dev-binding

subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-admin

rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","list","create","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-admin-binding

subjects:
  - kind: User
    name: cluster-admin-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev
  apiGroup: rbac.authorization.k8s.io
