apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
    - system:authetnticated
  usages:
    - digital signature
    - key encipherment
    - client auth
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXEvV05UblMzTWxya1djZHFtVVZ5OW4reTgrTUliNWdCRVlwUzNYUzR1eTE1CjkyYTJVbFErQ0pHZUdhQlBWMS9XV2JuZ3JUWDJSVHhNRVR0VHVaalh3Sk5FbnFmdFQ3eVZhcmFjZkdjQlhsTEcKczlmSDBmMno2d2J2S3kvOUkvSDkxV1M2YzJZNFBQYWk2RERTSFMzSy9tNUJqWko3T0djYURoWTZmOHdOQkc2bwpzOWNtNkw3R3VzSkJLMFJpKzZUbElFaVkxV3FscXcxeFVqMGlQK1U1bVZUOCtTeEh0ZHYrYWlZQ1hoQ3FSVGVtCkJCNXZZQTRUd1hLeWZjT1JzUWg3TjlVc0UzNzhFL1dvN0ZIU1FrOTlaZFFlNmtnclFNVDROczFoY1M2WUhPcWgKVk8wYjlFYTNGOXJ2VjJFYnZKTGFRQkVqUTdVWGdyTytNMGEwdnFoc0lRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRlRGUVZVVHBVTExGNjVDRUI2OTFLY1M5Zkl3TzFoaExtWGJMN3JHU1AxWkxQWFlzU09RClUrYjZHRUVyM3hCa1NOR3NVdEU4RVAyalNZc3JSaitGMk5VMzI4ZEdQdnM0blNZMmVHUmdHcGtFTUlqVmFkdXUKWjA2aUdDWnJqS3cycHpkYkRocmtzTEVPMm1KMjhaL0FuZ2ZxVXpnMUVVajFHTXhkM3JhNC9tNkpYMVRpQUkyNQpNYm8wdVNlYmt5OFZqQVpkR0ZCYkVXbzdESEFFTm5KSmJqdmtiQVMycjlmN2tRTklyaXZGUlM1MWJLWSs2RzZCClN2N3ozSnBJNEs3WmhadkFPUlFFTERaZlgxMlVHcU1HcmpoYlNRcVBtSXl2bDlUZVZ3MG80VU1jQ0tIWTZBdkQKNUcvYUpOT1lkQmV1RHBQNGxMK0FVRDN1SXpoRWhHVnFSZXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
                                                           