---
#PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  accessModes:
    - ReadWriteOnce #Another oprions: RWO/ROX(ReadOnlyMany)/RWX/ReadWriteOncePod
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
    type: Directory

---
#PVCs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-volume1
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # or <Delete>, or <Recycle>(DEPRECATED)
  resources:
    requests:
      storage: 500Mi

---
apiVersion : v1
kind: Pod
metadata:
  name: my-app
  labels:
    env  : prod
    app  : main
    tier : frontend
    owner: svs
spec:
  containers:
    - name : container-web
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /opt
          name: data-volume
  volumes: # Not recomendet for multinodes cluster
    - name: data-volume
      PersistentVolumeClaim:
        claimName: claim-volume1





